spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mkk
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    change-log: classpath:/db.changelog/db-changelog-master.xml

security:
  jwt:
    token:
      secret-key: mkkproject
      expire-length: 36000
      refresh-token-expire-length: 604800

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
